
source 'https://github.com/pirder/cocoapod-repo.git'

use_modular_headers!

platform :ios, '10.0'

target 'OptimisationCrashDemo' do
  use_modular_headers!
  pod 'OptimisationPodLib'
# pod 'UtilLib', :path => './UtilLib'

end
